// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq5ojXcVs7Tl7eh4G81r2cqpJhRyFFeDo',
    appId: '1:944995292987:android:5e6d08e9fb08af1f2e891e',
    messagingSenderId: '944995292987',
    projectId: 'simcast-3d821',
    storageBucket: 'simcast-3d821.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjKKMRmOR0Eda-a7gKnDC35Bvihv85eLs',
    appId: '1:944995292987:ios:610ed000b36af8b22e891e',
    messagingSenderId: '944995292987',
    projectId: 'simcast-3d821',
    storageBucket: 'simcast-3d821.firebasestorage.app',
    iosBundleId: 'com.rowaidx.simcast',
  );

}